# Generated by Django 6.0.6 on 2026-07-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order', 'Order'), ('payment', 'Payment'), ('chat', 'Chat'), ('promo', 'Promo'), ('system', 'System'), ('follow', 'Follow'), ('review', 'Review'), ('product', 'Product'), ('inventory', 'Inventory'), ('ai_scan', 'AI Scan'), ('flash_sale', 'Flash Sale'), ('loyalty', 'Loyalty'), ('voucher', 'Voucher'), ('security', 'Security'), ('delivery', 'Delivery'), ('wallet', 'Wallet'), ('report', 'Report')], default='system', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent'), ('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
    ]
