# Generated by Django 6.0.5 on 2026-05-22 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_products_sold', models.IntegerField(default=0)),
                ('new_customers_count', models.IntegerField(default=0)),
                ('total_visitors', models.IntegerField(default=0)),
                ('top_product_id', models.IntegerField(blank=True, null=True)),
                ('top_product_name', models.CharField(blank=True, max_length=150, null=True)),
                ('top_product_sales', models.IntegerField(default=0)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('revenue_growth', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_completed', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='stores.store')),
            ],
            options={
                'verbose_name': 'Laporan Harian',
                'verbose_name_plural': 'Laporan Harian',
                'db_table': 'daily_reports',
                'unique_together': {('store', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DeviceAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop')], max_length=20)),
                ('browser', models.CharField(blank=True, max_length=50, null=True)),
                ('os', models.CharField(blank=True, max_length=50, null=True)),
                ('visitors_count', models.IntegerField(default=0)),
                ('page_views', models.IntegerField(default=0)),
                ('bounce_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_analytics', to='stores.store')),
            ],
            options={
                'verbose_name': 'Analitik Perangkat',
                'verbose_name_plural': 'Analitik Perangkat',
                'db_table': 'device_analytics',
                'indexes': [models.Index(fields=['store', 'date'], name='device_anal_store_i_03fb8e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalesAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_products_sold', models.IntegerField(default=0)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('new_customers', models.IntegerField(default=0)),
                ('returning_customers', models.IntegerField(default=0)),
                ('hourly_sales', models.JSONField(blank=True, default=dict)),
                ('hourly_orders', models.JSONField(blank=True, default=list)),
                ('payment_methods', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_analytics', to='stores.store')),
            ],
            options={
                'verbose_name': 'Analitik Penjualan',
                'verbose_name_plural': 'Analitik Penjualan',
                'db_table': 'sales_analytics',
                'indexes': [models.Index(fields=['store', 'date'], name='sales_analy_store_i_375cdc_idx'), models.Index(fields=['date'], name='sales_analy_date_01a904_idx')],
                'unique_together': {('store', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('page_view', 'Page View'), ('search', 'Search'), ('add_to_cart', 'Add to Cart'), ('checkout', 'Checkout'), ('purchase', 'Purchase'), ('review', 'Review'), ('follow_store', 'Follow Store'), ('share', 'Share')], max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, max_length=20, null=True)),
                ('page_url', models.TextField(blank=True, null=True)),
                ('referrer', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_activities', to='stores.store')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aktivitas Pengguna',
                'verbose_name_plural': 'Aktivitas Pengguna',
                'db_table': 'user_activities',
                'indexes': [models.Index(fields=['store', 'activity_type'], name='user_activi_store_i_b2292f_idx'), models.Index(fields=['created_at'], name='user_activi_created_9fa3ca_idx'), models.Index(fields=['activity_type'], name='user_activi_activit_534635_idx')],
            },
        ),
    ]
