# Generated by Django 6.0.6 on 2026-07-06 01:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='district',
            new_name='regions_dis_regency_fe149f_idx',
            old_name='regions_dis_regency_6e5e4f_idx',
        ),
        migrations.RenameIndex(
            model_name='district',
            new_name='regions_dis_provinc_22e5b0_idx',
            old_name='regions_dis_provinc_3b48ed_idx',
        ),
        migrations.RenameIndex(
            model_name='regency',
            new_name='regions_reg_provinc_a85420_idx',
            old_name='regions_reg_provinc_1b50cc_idx',
        ),
        migrations.RenameIndex(
            model_name='village',
            new_name='regions_vil_distric_d65246_idx',
            old_name='regions_vil_distric_8fa806_idx',
        ),
        migrations.RenameIndex(
            model_name='village',
            new_name='regions_vil_postal__e19bf8_idx',
            old_name='regions_vil_postal_abdef0_idx',
        ),
        migrations.RenameIndex(
            model_name='village',
            new_name='regions_vil_name_up_9a3b94_idx',
            old_name='regions_vil_name_up_0142a6_idx',
        ),
        migrations.AlterField(
            model_name='district',
            name='code',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Kode Kemendagri'),
        ),
        migrations.AlterField(
            model_name='province',
            name='code',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Kode Kemendagri'),
        ),
        migrations.AlterField(
            model_name='regency',
            name='code',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Kode Kemendagri'),
        ),
        migrations.AlterField(
            model_name='village',
            name='code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Kode BPS'),
        ),
    ]
