# Generated by Django 6.0.5 on 2026-05-22 12:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Judul')),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True, verbose_name='Subjudul')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Gambar Banner')),
                ('link_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL Tautan')),
                ('link_text', models.CharField(default='Belanja Sekarang', max_length=100, verbose_name='Teks Tautan')),
                ('position', models.CharField(choices=[('help_hero', 'Help Hero'), ('help_bottom', 'Help Bottom'), ('home_hero', 'Home Hero'), ('sidebar', 'Sidebar')], default='help_hero', max_length=30, verbose_name='Posisi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Urutan')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Mulai')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Selesai')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner Promo',
                'verbose_name_plural': 'Banner Promo',
                'db_table': 'banner_promos',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ChatQuickReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('order', 'Status Pesanan'), ('payment', 'Pembayaran'), ('return', 'Pengembalian Barang'), ('other', 'Lainnya')], max_length=20, verbose_name='Kategori')),
                ('label', models.CharField(max_length=100, verbose_name='Label Tombol')),
                ('message_template', models.TextField(verbose_name='Template Pesan')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Urutan')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Balasan Cepat Chat',
                'verbose_name_plural': 'Balasan Cepat Chat',
                'db_table': 'chat_quick_replies',
                'ordering': ['category', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('phone', 'Telepon'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('telegram', 'Telegram'), ('line', 'LINE')], max_length=30, unique=True, verbose_name='Tipe Kontak')),
                ('label', models.CharField(max_length=100, verbose_name='Label')),
                ('value', models.CharField(max_length=255, verbose_name='Nilai Kontak')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ikon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Urutan')),
                ('operating_hours', models.CharField(blank=True, help_text='Contoh: Senin - Jumat, 08:00 - 20:00', max_length=255, null=True, verbose_name='Jam Operasional')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Info Kontak',
                'verbose_name_plural': 'Info Kontak',
                'db_table': 'contact_infos',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HelpCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Kategori')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('icon', models.CharField(blank=True, help_text='CSS class or emoji', max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Urutan')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kategori Bantuan',
                'verbose_name_plural': 'Kategori Bantuan',
                'db_table': 'help_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SupportInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Key')),
                ('title', models.CharField(max_length=255, verbose_name='Judul')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ikon')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Urutan')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Info Dukungan',
                'verbose_name_plural': 'Info Dukungan',
                'db_table': 'support_infos',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Pertanyaan')),
                ('answer', models.TextField(verbose_name='Jawaban')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Urutan')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='support.helpcategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'db_table': 'faqs',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Judul')),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('content', models.TextField(verbose_name='Konten')),
                ('excerpt', models.TextField(blank=True, null=True, verbose_name='Ringkasan')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='help/articles/')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='help/attachments/')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Jumlah Dilihat')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='Membantu')),
                ('not_helpful_count', models.PositiveIntegerField(default=0, verbose_name='Tidak Membantu')),
                ('is_published', models.BooleanField(default=True, verbose_name='Dipublikasi')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Unggulan')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Urutan')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tanggal Publikasi')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Penulis')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='support.helpcategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Artikel Bantuan',
                'verbose_name_plural': 'Artikel Bantuan',
                'db_table': 'help_articles',
                'ordering': ['-is_featured', 'sort_order', '-published_at'],
                'indexes': [models.Index(fields=['slug'], name='help_articl_slug_cc9d3f_idx'), models.Index(fields=['category', 'is_published'], name='help_articl_categor_ee7b1e_idx'), models.Index(fields=['views_count'], name='help_articl_views_c_71e609_idx')],
            },
        ),
    ]
