# Generated by Django 6.0.5 on 2026-05-22 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='Chat Bantuan', max_length=255, verbose_name='Subjek')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Selesai')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'Percakapan Dukungan',
                'verbose_name_plural': 'Percakapan Dukungan',
                'db_table': 'support_conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Pesan')),
                ('is_from_user', models.BooleanField(default=True, verbose_name='Dari Pengguna')),
                ('is_read', models.BooleanField(default=False, verbose_name='Terbaca')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='support/attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportconversation', verbose_name='Percakapan')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to=settings.AUTH_USER_MODEL, verbose_name='Pengirim')),
            ],
            options={
                'verbose_name': 'Pesan Dukungan',
                'verbose_name_plural': 'Pesan Dukungan',
                'db_table': 'support_messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='support_mes_convers_c7d2f0_idx'), models.Index(fields=['is_read'], name='support_mes_is_read_445968_idx')],
            },
        ),
    ]
