# Generated by Django 4.2.30 on 2026-06-02 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0002_supportconversation_supportmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Subjek')),
                ('message', models.TextField(verbose_name='Pesan')),
                ('support_status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('resolved', 'Resolved')], default='open', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20, verbose_name='Prioritas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'Tiket Dukungan',
                'verbose_name_plural': 'Tiket Dukungan',
                'db_table': 'supports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='supports_user_id_b14d68_idx'), models.Index(fields=['support_status'], name='supports_support_6dae3e_idx'), models.Index(fields=['created_at'], name='supports_created_ad314a_idx')],
            },
        ),
    ]
