# Generated by Django 6.0.6 on 2026-07-25 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_add_performance_indexes'),
        ('products', '0009_add_fulltext_search_index'),
        ('stores', '0004_alter_store_city'),
        ('support', '0004_repair_supports_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(choices=[('product_not_as_described', 'Produk Tidak Sesuai'), ('damaged_product', 'Produk Rusak'), ('expired_product', 'Produk Kadaluwarsa'), ('missing_items', 'Barang Kurang'), ('wrong_items', 'Barang Salah'), ('late_delivery', 'Terlambat'), ('seller_unresponsive', 'Penjual Tidak Responsif'), ('other', 'Lainnya')], max_length=40, verbose_name='Tipe Komplain')),
                ('description', models.TextField(verbose_name='Deskripsi')),
                ('desired_resolution', models.TextField(blank=True, null=True, verbose_name='Resolusi Diinginkan')),
                ('attachment_1', models.FileField(blank=True, null=True, upload_to='complaints/')),
                ('attachment_2', models.FileField(blank=True, null=True, upload_to='complaints/')),
                ('attachment_3', models.FileField(blank=True, null=True, upload_to='complaints/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('resolution_notes', models.TextField(blank=True, null=True, verbose_name='Catatan Resolusi')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Komplain',
                'verbose_name_plural': 'Komplain',
                'db_table': 'complaints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispute_type', models.CharField(choices=[('refund', 'Refund'), ('return', 'Pengembalian Barang'), ('cancellation', 'Pembatalan'), ('quality', 'Kualitas Produk'), ('delivery', 'Pengiriman'), ('other', 'Lainnya')], max_length=20, verbose_name='Tipe Sengketa')),
                ('description', models.TextField(verbose_name='Deskripsi')),
                ('desired_outcome', models.TextField(blank=True, null=True, verbose_name='Hasil Diinginkan')),
                ('evidence_notes', models.TextField(blank=True, null=True, verbose_name='Catatan Bukti')),
                ('status', models.CharField(choices=[('opened', 'Dibuka'), ('investigation', 'Investigasi'), ('mediation', 'Mediasi'), ('resolved', 'Selesai'), ('escalated', 'Naik Banding')], default='opened', max_length=20, verbose_name='Status')),
                ('resolution', models.CharField(blank=True, choices=[('buyer_win', 'Pembeli Menang'), ('seller_win', 'Penjual Menang'), ('partial', 'Sebagian'), ('cancelled', 'Dibatalkan')], max_length=20, null=True, verbose_name='Resolusi')),
                ('resolution_notes', models.TextField(blank=True, null=True, verbose_name='Catatan Resolusi')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sengketa',
                'verbose_name_plural': 'Sengketa',
                'db_table': 'disputes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('ticket', 'Tiket'), ('complaint', 'Komplain'), ('dispute', 'Sengketa'), ('report', 'Laporan')], max_length=20, verbose_name='Tipe')),
                ('reference_id', models.IntegerField(verbose_name='ID Referensi')),
                ('content', models.TextField(verbose_name='Isi Catatan')),
                ('is_private', models.BooleanField(default=True, verbose_name='Internal Only')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catatan Internal',
                'verbose_name_plural': 'Catatan Internal',
                'db_table': 'internal_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportBuyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('fraud', 'Penipuan'), ('harassment', 'Pelecehan'), ('false_complaint', 'Komplain Palsu'), ('chargeback', 'Chargeback'), ('fake_review', 'Ulasan Palsu'), ('other', 'Lainnya')], max_length=30, verbose_name='Alasan')),
                ('description', models.TextField(verbose_name='Deskripsi')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='pending', max_length=20, verbose_name='Status')),
                ('moderation_notes', models.TextField(blank=True, null=True, verbose_name='Catatan Moderasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Laporan Pembeli',
                'verbose_name_plural': 'Laporan Pembeli',
                'db_table': 'report_buyers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('illegal', 'Barang Ilegal'), ('prohibited', 'Barang Terlarang'), ('counterfeit', 'Barang Palsu'), ('misleading', 'Informasi Menyesatkan'), ('inappropriate', 'Konten Tidak Pantas'), ('spam', 'Spam'), ('fraud', 'Penipuan'), ('other', 'Lainnya')], max_length=30, verbose_name='Alasan')),
                ('description', models.TextField(verbose_name='Deskripsi')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='pending', max_length=20, verbose_name='Status')),
                ('moderation_notes', models.TextField(blank=True, null=True, verbose_name='Catatan Moderasi')),
                ('risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Skor Risiko')),
                ('is_auto_flagged', models.BooleanField(default=False, verbose_name='Auto Flag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Laporan Produk',
                'verbose_name_plural': 'Laporan Produk',
                'db_table': 'report_products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('fraud', 'Penipuan'), ('counterfeit', 'Barang Palsu'), ('harassment', 'Pelecehan'), ('spam', 'Spam'), ('bad_service', 'Pelayanan Buruk'), ('prohibited_items', 'Menjual Barang Terlarang'), ('fake_reviews', 'Ulasan Palsu'), ('other', 'Lainnya')], max_length=30, verbose_name='Alasan')),
                ('description', models.TextField(verbose_name='Deskripsi')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='pending', max_length=20, verbose_name='Status')),
                ('moderation_notes', models.TextField(blank=True, null=True, verbose_name='Catatan Moderasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Laporan Penjual',
                'verbose_name_plural': 'Laporan Penjual',
                'db_table': 'report_sellers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='supportticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Ditugaskan Ke'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='support/tickets/', verbose_name='Lampiran'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('order', 'Pesanan'), ('payment', 'Pembayaran'), ('refund', 'Refund'), ('complaint', 'Komplain'), ('report', 'Laporan'), ('technical', 'Teknis'), ('account', 'Akun'), ('ai_escalation', 'AI Escalation')], default='general', max_length=30, verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='csat_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Umpan Balik CSAT'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='csat_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Skor CSAT'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Respon Pertama'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Selesai Pada'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Batas SLA'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='sla_met',
            field=models.BooleanField(default=False, verbose_name='SLA Terpenuhi'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='support_status',
            field=models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('solved', 'Solved'), ('closed', 'Closed')], default='open', max_length=20, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['assigned_to'], name='supports_assigne_8f05c8_idx'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Ditugaskan Ke'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='orders.order', verbose_name='Pesanan'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='against_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_against', to=settings.AUTH_USER_MODEL, verbose_name='Terhadap'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='mediator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mediated_disputes', to=settings.AUTH_USER_MODEL, verbose_name='Mediator'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='opened_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opened_disputes', to=settings.AUTH_USER_MODEL, verbose_name='Dibuka Oleh'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='orders.order', verbose_name='Pesanan'),
        ),
        migrations.AddField(
            model_name='internalnote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_notes', to=settings.AUTH_USER_MODEL, verbose_name='Penulis'),
        ),
        migrations.AddField(
            model_name='reportbuyer',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_reports', to=settings.AUTH_USER_MODEL, verbose_name='Pembeli'),
        ),
        migrations.AddField(
            model_name='reportbuyer',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_buyers', to=settings.AUTH_USER_MODEL, verbose_name='Dimoderasi Oleh'),
        ),
        migrations.AddField(
            model_name='reportbuyer',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_reports', to='orders.order', verbose_name='Pesanan'),
        ),
        migrations.AddField(
            model_name='reportbuyer',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_buyers', to=settings.AUTH_USER_MODEL, verbose_name='Pelapor (Seller)'),
        ),
        migrations.AddField(
            model_name='reportproduct',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_products', to=settings.AUTH_USER_MODEL, verbose_name='Dimoderasi Oleh'),
        ),
        migrations.AddField(
            model_name='reportproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='products.product', verbose_name='Produk'),
        ),
        migrations.AddField(
            model_name='reportproduct',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_products', to=settings.AUTH_USER_MODEL, verbose_name='Pelapor'),
        ),
        migrations.AddField(
            model_name='reportseller',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_sellers', to=settings.AUTH_USER_MODEL, verbose_name='Dimoderasi Oleh'),
        ),
        migrations.AddField(
            model_name='reportseller',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_sellers', to=settings.AUTH_USER_MODEL, verbose_name='Pelapor'),
        ),
        migrations.AddField(
            model_name='reportseller',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_reports', to=settings.AUTH_USER_MODEL, verbose_name='Penjual'),
        ),
        migrations.AddField(
            model_name='reportseller',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='stores.store', verbose_name='Toko'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['user', 'status'], name='complaints_user_id_55f4a4_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['order'], name='complaints_order_i_219db2_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['order', 'status'], name='disputes_order_i_31e8ee_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['opened_by'], name='disputes_opened__edb769_idx'),
        ),
        migrations.AddIndex(
            model_name='internalnote',
            index=models.Index(fields=['note_type', 'reference_id'], name='internal_no_note_ty_be9ea9_idx'),
        ),
        migrations.AddIndex(
            model_name='internalnote',
            index=models.Index(fields=['author'], name='internal_no_author__8a100a_idx'),
        ),
        migrations.AddIndex(
            model_name='reportbuyer',
            index=models.Index(fields=['buyer', 'status'], name='report_buye_buyer_i_a4e784_idx'),
        ),
        migrations.AddIndex(
            model_name='reportbuyer',
            index=models.Index(fields=['reporter'], name='report_buye_reporte_6737ee_idx'),
        ),
        migrations.AddIndex(
            model_name='reportproduct',
            index=models.Index(fields=['product', 'status'], name='report_prod_product_da1c99_idx'),
        ),
        migrations.AddIndex(
            model_name='reportproduct',
            index=models.Index(fields=['reporter'], name='report_prod_reporte_fa20ef_idx'),
        ),
        migrations.AddIndex(
            model_name='reportseller',
            index=models.Index(fields=['seller', 'status'], name='report_sell_seller__87965a_idx'),
        ),
        migrations.AddIndex(
            model_name='reportseller',
            index=models.Index(fields=['reporter'], name='report_sell_reporte_3f132d_idx'),
        ),
    ]
