# Generated by Django 6.0.5 on 2026-05-22 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('gopay', 'GoPay'), ('shopeepay', 'ShopeePay'), ('ovo', 'OVO'), ('dana', 'DANA'), ('linkaja', 'LinkAja'), ('qris', 'QRIS'), ('cod', 'Cash on Delivery')], max_length=50)),
                ('display_name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fee_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Metode Pembayaran',
                'verbose_name_plural': 'Metode Pembayaran',
                'db_table': 'payment_methods',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('transaction_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('midtrans_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('midtrans_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('va_number', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_response', models.JSONField(blank=True, default=dict, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pembayaran',
                'verbose_name_plural': 'Pembayaran',
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='MidtransTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_status', models.CharField(choices=[('pending', 'Pending'), ('settlement', 'Settlement'), ('capture', 'Capture'), ('deny', 'Deny'), ('cancel', 'Cancel'), ('expire', 'Expire'), ('refund', 'Refund'), ('partial_refund', 'Partial Refund'), ('authorize', 'Authorize')], default='pending', max_length=20)),
                ('transaction_time', models.DateTimeField(blank=True, null=True)),
                ('settlement_time', models.DateTimeField(blank=True, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('bank', models.CharField(blank=True, max_length=50, null=True)),
                ('va_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_key', models.CharField(blank=True, max_length=100, null=True)),
                ('biller_code', models.CharField(blank=True, max_length=100, null=True)),
                ('status_code', models.CharField(blank=True, max_length=10, null=True)),
                ('status_message', models.TextField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict, null=True)),
                ('fraud_status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='midtrans', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Transaksi Midtrans',
                'verbose_name_plural': 'Transaksi Midtrans',
                'db_table': 'midtrans_transactions',
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_code'], name='payments_transac_d0167a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_status'], name='payments_payment_bbdde9_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order'], name='payments_order_i_b32b33_idx'),
        ),
        migrations.AddIndex(
            model_name='midtranstransaction',
            index=models.Index(fields=['order_id'], name='midtrans_tr_order_i_7ef05e_idx'),
        ),
        migrations.AddIndex(
            model_name='midtranstransaction',
            index=models.Index(fields=['transaction_status'], name='midtrans_tr_transac_42284a_idx'),
        ),
    ]
