# Generated by Django 4.2.30 on 2026-06-23 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_store_options'),
        ('orders', '0004_add_cart_ordering'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order'),
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50, verbose_name='Nama Bank')),
                ('account_number', models.CharField(max_length=50, verbose_name='Nomor Rekening')),
                ('account_holder', models.CharField(max_length=100, verbose_name='Nama Pemilik Rekening')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Rekening Utama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='stores.store')),
            ],
            options={
                'verbose_name': 'Rekening Bank',
                'verbose_name_plural': 'Rekening Bank',
                'db_table': 'bank_accounts',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
    ]
