# Generated by Django 6.0.6 on 2026-07-01 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_admin_fee_field'),
        ('payments', '0002_alter_payment_order_bankaccount'),
        ('stores', '0002_alter_store_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminFeeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jumlah Fee')),
                ('payout_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20, verbose_name='Status Pencairan')),
                ('owner_phone', models.CharField(default='089667850425', max_length=20, verbose_name='No. HP Owner (E-Wallet)')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_fee_record', to='orders.order', verbose_name='Pesanan')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_fees', to='stores.store', verbose_name='Toko')),
            ],
            options={
                'verbose_name': 'Fee Admin',
                'verbose_name_plural': 'Fee Admin',
                'db_table': 'admin_fee_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
