# Generated by Django 6.0.6 on 2026-07-06 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_wallet_and_transactions'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='wallettransaction',
            new_name='wallet_tran_wallet__3d47ad_idx',
            old_name='wallet_txn_wallet_created_idx',
        ),
        migrations.RenameIndex(
            model_name='wallettransaction',
            new_name='wallet_tran_user_id_1da2e3_idx',
            old_name='wallet_txn_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='wallettransaction',
            new_name='wallet_tran_tx_type_85d2f7_idx',
            old_name='wallet_txn_tx_type_idx',
        ),
    ]
