# Generated by Django 6.0.6 on 2026-07-27 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_add_performance_indexes'),
        ('stores', '0004_alter_store_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Rekening utama yang telah terverifikasi dan menjadi tujuan pencairan dana', verbose_name='Terverifikasi'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Terverifikasi Pada'),
        ),
        migrations.CreateModel(
            name='BankAccountChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_bank_name', models.CharField(max_length=50, verbose_name='Bank Lama')),
                ('old_account_number', models.CharField(max_length=50, verbose_name='No. Rekening Lama')),
                ('old_account_holder', models.CharField(max_length=100, verbose_name='Pemilik Rekening Lama')),
                ('new_bank_name', models.CharField(max_length=50, verbose_name='Bank Baru')),
                ('new_account_number', models.CharField(max_length=50, verbose_name='No. Rekening Baru')),
                ('new_account_holder', models.CharField(max_length=100, verbose_name='Pemilik Rekening Baru')),
                ('status', models.CharField(choices=[('pending_otp', 'Menunggu Verifikasi OTP'), ('pending_password', 'Menunggu Konfirmasi Password'), ('pending_approval', 'Menunggu Persetujuan'), ('pending_waiting_period', 'Masa Tunggu'), ('approved', 'Disetujui'), ('completed', 'Selesai'), ('rejected', 'Ditolak'), ('cancelled', 'Dibatalkan'), ('expired', 'Kadaluwarsa')], default='pending_otp', max_length=30, verbose_name='Status')),
                ('otp_verified', models.BooleanField(default=False, verbose_name='OTP Terverifikasi')),
                ('password_verified', models.BooleanField(default=False, verbose_name='Password Terverifikasi')),
                ('otp_verified_at', models.DateTimeField(blank=True, null=True)),
                ('password_verified_at', models.DateTimeField(blank=True, null=True)),
                ('otp_code_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('verification_token', models.CharField(blank=True, max_length=255, null=True)),
                ('waiting_period_hours', models.IntegerField(default=24, verbose_name='Masa Tunggu (Jam)')),
                ('waiting_started_at', models.DateTimeField(blank=True, null=True)),
                ('waiting_ends_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('requires_admin_approval', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_account_changes', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_change_requests', to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permintaan Perubahan Rekening',
                'verbose_name_plural': 'Permintaan Perubahan Rekening',
                'db_table': 'bank_account_change_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', 'status'], name='bank_accoun_store_i_2e7123_idx'), models.Index(fields=['user', 'created_at'], name='bank_accoun_user_id_8ebfbb_idx'), models.Index(fields=['status'], name='bank_accoun_status_cf3980_idx')],
            },
        ),
    ]
