# Generated by Django 6.0.6 on 2026-07-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeoMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, help_text="URL path, e.g. '/info/tentang-kami/' or '/' for root", max_length=500, unique=True)),
                ('meta_title', models.CharField(blank=True, help_text='HTML <title> tag (max 120 chars for SEO)', max_length=120)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description (aim for 155-160 chars, max 320)', max_length=320)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=500)),
                ('og_title', models.CharField(blank=True, help_text='Open Graph title (defaults to meta_title if empty)', max_length=120)),
                ('og_description', models.TextField(blank=True, help_text='Open Graph description (defaults to meta_description if empty)', max_length=320)),
                ('og_image', models.URLField(blank=True, help_text='Open Graph image URL (e.g., /static/images/og-default.png)', max_length=500)),
                ('canonical_url', models.CharField(blank=True, help_text='Custom canonical URL (leave empty to auto-generate from path)', max_length=500)),
                ('noindex', models.BooleanField(default=False, help_text='Check to add noindex, nofollow to this page')),
                ('schema_type', models.CharField(choices=[('WebPage', 'WebPage'), ('AboutPage', 'AboutPage'), ('ContactPage', 'ContactPage'), ('FAQPage', 'FAQPage'), ('Blog', 'Blog'), ('Article', 'Article'), ('Product', 'Product'), ('CollectionPage', 'CollectionPage'), ('SearchResultsPage', 'SearchResultsPage'), ('ItemPage', 'ItemPage'), ('ProfilePage', 'ProfilePage')], default='WebPage', help_text='Schema.org @type for this page', max_length=50)),
                ('breadcrumb_json', models.TextField(blank=True, help_text='JSON array of breadcrumb items, e.g. [{"label":"Home","url":"/"}]')),
                ('hreflang_json', models.TextField(blank=True, help_text='JSON object of hreflang alternates, e.g. {"en":"/en/about/"}')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to use hardcoded defaults')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Metadata',
                'verbose_name_plural': 'SEO Metadata',
                'ordering': ['path'],
            },
        ),
    ]
