# Generated by Django 6.0.5 on 2026-05-22 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Kategori Toko',
                'verbose_name_plural': 'Kategori Toko',
                'db_table': 'store_categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100, verbose_name='Nama Toko')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategori')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Alamat')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kota')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='Provinsi')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('delivery_type', models.CharField(blank=True, max_length=100, null=True)),
                ('service_area', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_owner', models.CharField(blank=True, max_length=100, null=True)),
                ('store_logo', models.ImageField(blank=True, null=True, upload_to='stores/logos/', verbose_name='Logo Toko')),
                ('store_banner', models.ImageField(blank=True, null=True, upload_to='stores/banners/', verbose_name='Banner Toko')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20, verbose_name='Status')),
                ('follower_count', models.IntegerField(default=0)),
                ('product_count', models.IntegerField(default=0)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Toko',
                'verbose_name_plural': 'Toko',
                'db_table': 'stores',
            },
        ),
        migrations.CreateModel(
            name='StoreFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pengikut Toko',
                'verbose_name_plural': 'Pengikut Toko',
                'db_table': 'store_followers',
            },
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['store_name'], name='stores_store_n_99cccc_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['city'], name='stores_city_8e8d52_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['status'], name='stores_status_ecb921_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['rating_avg'], name='stores_rating__a94ed6_idx'),
        ),
        migrations.AddIndex(
            model_name='storefollower',
            index=models.Index(fields=['user', 'store'], name='store_follo_user_id_cae058_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storefollower',
            unique_together={('user', 'store')},
        ),
    ]
