# Generated by Django 4.2.30 on 2026-06-07 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['store_name'], 'verbose_name': 'Toko', 'verbose_name_plural': 'Toko'},
        ),
    ]
