# Generated by manage.py makemigrations --merge stores
# Manual creation: merges two parallel 0002 migration branches.

from django.db import migrations


class Migration(migrations.Migration):
    """Merge two parallel 0002 migration branches in stores app."""

    dependencies = [
        ('stores', '0002_alter_store_options'),
        ('stores', '0002_store_district_village_fields'),
    ]

    operations = [
    ]
