# Generated by Django 6.0.6 on 2026-07-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_merge_20260703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kota/Kabupaten'),
        ),
    ]
