# Generated by Django 6.0.6 on 2026-06-29 00:44

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_socialaccount'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndonesianAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=100, verbose_name='Provinsi')),
                ('province_code', models.CharField(blank=True, max_length=2, verbose_name='Kode Provinsi')),
                ('city', models.CharField(max_length=100, verbose_name='Kota/Kabupaten')),
                ('city_code', models.CharField(blank=True, max_length=4, verbose_name='Kode Kota')),
                ('district', models.CharField(max_length=100, verbose_name='Kecamatan')),
                ('district_code', models.CharField(blank=True, max_length=6, verbose_name='Kode Kecamatan')),
                ('village', models.CharField(blank=True, max_length=100, verbose_name='Kelurahan/Desa')),
                ('village_code', models.CharField(blank=True, max_length=10, verbose_name='Kode Desa')),
                ('street', models.TextField(verbose_name='Jalan / Detail Alamat')),
                ('postal_code', models.CharField(blank=True, max_length=5, verbose_name='Kode Pos')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alamat Indonesia',
                'verbose_name_plural': 'Alamat Indonesia',
                'db_table': 'indonesian_addresses',
            },
        ),
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(help_text='Nomor Induk Kependudukan (16 digit)', max_length=16, unique=True, verbose_name='NIK')),
                ('full_name_on_ktp', models.CharField(max_length=150, verbose_name='Nama di KTP')),
                ('birth_place', models.CharField(blank=True, max_length=100, verbose_name='Tempat Lahir')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Laki-laki'), ('female', 'Perempuan')], max_length=10, verbose_name='Jenis Kelamin')),
                ('religion', models.CharField(blank=True, choices=[('islam', 'Islam'), ('kristen', 'Kristen Protestan'), ('katholik', 'Kristen Katolik'), ('hindu', 'Hindu'), ('buddha', 'Buddha'), ('konghucu', 'Konghucu'), ('other', 'Lainnya')], max_length=20, verbose_name='Agama')),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Belum Menikah'), ('married', 'Menikah'), ('divorced', 'Cerai'), ('widowed', 'Cerai Mati')], max_length=20, verbose_name='Status Pernikahan')),
                ('ktp_address', models.TextField(blank=True, verbose_name='Alamat KTP')),
                ('ktp_province', models.CharField(blank=True, max_length=100)),
                ('ktp_city', models.CharField(blank=True, max_length=100)),
                ('ktp_district', models.CharField(blank=True, max_length=100)),
                ('ktp_postal_code', models.CharField(blank=True, max_length=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Terverifikasi'), ('rejected', 'Ditolak'), ('expired', 'Kadaluwarsa')], default='pending', max_length=20)),
                ('verification_method', models.CharField(blank=True, choices=[('manual', 'Verifikasi Manual'), ('ocr', 'OCR Otomatis'), ('api', 'API Pihak Ketiga')], max_length=30)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Alasan Penolakan')),
                ('ktp_photo', models.ImageField(blank=True, null=True, upload_to='kyc/ktp/', verbose_name='Foto KTP')),
                ('selfie_photo', models.ImageField(blank=True, null=True, upload_to='kyc/selfie/', verbose_name='Foto Selfie dengan KTP')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nik_validation', models.JSONField(blank=True, default=dict, null=True, verbose_name='Hasil Validasi NIK')),
            ],
            options={
                'verbose_name': 'Verifikasi KYC',
                'verbose_name_plural': 'Verifikasi KYC',
                'db_table': 'kyc_verifications',
            },
        ),
        migrations.CreateModel(
            name='RegistrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('event_type', models.CharField(choices=[('start', 'Memulai Registrasi'), ('email_phone_submit', 'Submit Email/Phone'), ('otp_sent', 'OTP Terkirim'), ('otp_verified', 'OTP Terverifikasi'), ('profile_submit', 'Submit Profil'), ('store_setup', 'Setup Toko'), ('complete', 'Registrasi Selesai'), ('abandon', 'Meninggalkan Registrasi')], max_length=30)),
                ('role', models.CharField(blank=True, help_text='buyer/seller', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Detik sejak event sebelumnya', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Event Registrasi',
                'verbose_name_plural': 'Event Registrasi',
                'db_table': 'registration_events',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='device_fingerprint',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sidik Jari Perangkat'),
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.IntegerField(default=0, verbose_name='Gagal Login'),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Terkunci Hingga'),
        ),
        migrations.AddField(
            model_name='user',
            name='nik',
            field=models.CharField(blank=True, help_text='Nomor Induk Kependudukan (16 digit)', max_length=16, null=True, unique=True, verbose_name='NIK'),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Registrasi Selesai'),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Registrasi Dimulai'),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_step',
            field=models.CharField(choices=[('email_phone', 'Email/Phone'), ('otp', 'OTP'), ('profile', 'Profile'), ('store_setup', 'Store Setup'), ('complete', 'Complete')], default='email_phone', max_length=20, verbose_name='Langkah Registrasi'),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Nomor WhatsApp untuk OTP dan notifikasi', max_length=128, null=True, region=None, verbose_name='Nomor WhatsApp'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['nik'], name='users_nik_69b012_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['registration_step'], name='users_registr_0f46f3_idx'),
        ),
        migrations.AddIndex(
            model_name='indonesianaddress',
            index=models.Index(fields=['province'], name='indonesian__provinc_8c5a76_idx'),
        ),
        migrations.AddIndex(
            model_name='indonesianaddress',
            index=models.Index(fields=['city'], name='indonesian__city_3f10d1_idx'),
        ),
        migrations.AddIndex(
            model_name='indonesianaddress',
            index=models.Index(fields=['district'], name='indonesian__distric_098f0c_idx'),
        ),
        migrations.AddIndex(
            model_name='indonesianaddress',
            index=models.Index(fields=['postal_code'], name='indonesian__postal__9f1336_idx'),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_verifications', to=settings.AUTH_USER_MODEL, verbose_name='Diverifikasi Oleh'),
        ),
        migrations.AddField(
            model_name='registrationevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='kycverification',
            index=models.Index(fields=['nik'], name='kyc_verific_nik_fd59a3_idx'),
        ),
        migrations.AddIndex(
            model_name='kycverification',
            index=models.Index(fields=['status'], name='kyc_verific_status_0b0fb6_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationevent',
            index=models.Index(fields=['event_type'], name='registratio_event_t_3e0432_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationevent',
            index=models.Index(fields=['created_at'], name='registratio_created_19a703_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationevent',
            index=models.Index(fields=['email'], name='registratio_email_e35680_idx'),
        ),
    ]
