# Generated by Django 6.0.6 on 2026-07-25 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_otp_code_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Nama Role')),
                ('level', models.IntegerField(choices=[(100, 'Super Admin'), (80, 'Admin'), (60, 'Moderator'), (50, 'Support'), (40, 'Finance'), (30, 'Content Manager'), (10, 'Viewer')], unique=True, verbose_name='Level')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('permissions', models.JSONField(blank=True, default=list, help_text='Daftar permission yang dimiliki role ini', verbose_name='Permissions')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Role Administrator',
                'verbose_name_plural': 'Role Administrator',
                'db_table': 'admin_roles',
                'ordering': ['-level'],
            },
        ),
        migrations.CreateModel(
            name='AdminVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('otp_code', models.CharField(max_length=6, verbose_name='Kode OTP')),
                ('otp_code_hash', models.CharField(max_length=64, verbose_name='Hash OTP')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Terverifikasi'), ('expired', 'Kadaluwarsa')], default='pending', max_length=10)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_verifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verifikasi Admin',
                'verbose_name_plural': 'Verifikasi Admin',
                'db_table': 'admin_verifications',
            },
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_email', models.EmailField(max_length=254, verbose_name='Email Admin')),
                ('action', models.CharField(choices=[('login', 'Login'), ('login_failed', 'Login Gagal'), ('logout', 'Logout'), ('create_admin', 'Membuat Admin'), ('update_admin', 'Mengubah Admin'), ('delete_admin', 'Menghapus Admin'), ('activate_admin', 'Mengaktifkan Admin'), ('deactivate_admin', 'Menonaktifkan Admin'), ('change_password', 'Mengubah Password'), ('reset_password', 'Reset Password'), ('change_role', 'Mengubah Role'), ('verify_admin', 'Verifikasi Admin'), ('admin_verified_otp', 'Admin Verifikasi OTP'), ('system_config', 'Konfigurasi Sistem')], max_length=30, verbose_name='Aksi')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('target_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Target')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, max_length=20, null=True)),
                ('browser', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Detail')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Administrator')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Target')),
            ],
            options={
                'verbose_name': 'Log Audit Admin',
                'verbose_name_plural': 'Log Audit Admin',
                'db_table': 'admin_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin', 'created_at'], name='admin_audit_admin_i_fe5621_idx'), models.Index(fields=['action', 'created_at'], name='admin_audit_action_0be5f6_idx'), models.Index(fields=['created_at'], name='admin_audit_created_7f55c8_idx'), models.Index(fields=['admin_email'], name='admin_audit_admin_e_8416d5_idx')],
            },
        ),
    ]
