# Generated by Django 4.2.30 on 2026-06-02 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freshness_score', models.IntegerField(blank=True, help_text='0-100', null=True, verbose_name='Skor Kesegaran')),
                ('stock_status', models.CharField(blank=True, choices=[('sufficient', 'Sufficient'), ('low', 'Low'), ('critical', 'Critical')], max_length=100, null=True, verbose_name='Status Stok')),
                ('ai_result', models.TextField(blank=True, help_text='Raw AI analysis result', null=True, verbose_name='Hasil AI')),
                ('quality_status', models.CharField(choices=[('pending', 'Pending'), ('fresh', 'Fresh'), ('normal', 'Normal'), ('warning', 'Warning'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status Kualitas')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Cek')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='products.product', verbose_name='Produk')),
            ],
            options={
                'verbose_name': 'Pengecekan Kualitas',
                'verbose_name_plural': 'Pengecekan Kualitas',
                'db_table': 'quality_checks',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['product'], name='quality_che_product_a63d95_idx'), models.Index(fields=['quality_status'], name='quality_che_quality_262f7b_idx'), models.Index(fields=['checked_at'], name='quality_che_checked_aba250_idx')],
            },
        ),
    ]
