# Generated by Django 4.2.30 on 2026-06-07 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_qualitycheck'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Produk', 'verbose_name_plural': 'Produk'},
        ),
    ]
