# Generated by Django 6.0.6 on 2026-06-26 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options'),
        ('stores', '0002_alter_store_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Jumlah Diskon (Rp)'),
        ),
        migrations.AddField(
            model_name='promo',
            name='max_usage',
            field=models.IntegerField(default=0, help_text='0 = unlimited', verbose_name='Maksimum Penggunaan'),
        ),
        migrations.AddField(
            model_name='promo',
            name='min_purchase',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Minimum Belanja'),
        ),
        migrations.AddField(
            model_name='promo',
            name='promo_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kode Promo'),
        ),
        migrations.AddField(
            model_name='promo',
            name='promo_type',
            field=models.CharField(choices=[('free_shipping', 'Gratis Ongkir'), ('percentage', 'Diskon Persentase'), ('fixed', 'Diskon Nominal'), ('flash_sale', 'Flash Sale'), ('buy_x_get_y', 'Beli X Gratis Y')], default='percentage', max_length=30, verbose_name='Jenis Promo'),
        ),
        migrations.AddField(
            model_name='promo',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promos', to='stores.store', verbose_name='Toko'),
        ),
        migrations.AddField(
            model_name='promo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='usage_count',
            field=models.IntegerField(default=0, verbose_name='Jumlah Penggunaan'),
        ),
        migrations.AddField(
            model_name='review',
            name='seller_reply',
            field=models.TextField(blank=True, null=True, verbose_name='Balasan Penjual'),
        ),
        migrations.AddField(
            model_name='review',
            name='seller_reply_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Balasan'),
        ),
        migrations.AddConstraint(
            model_name='promo',
            constraint=models.UniqueConstraint(fields=('store', 'promo_code'), name='unique_store_promo_code'),
        ),
    ]
