# Generated by Django 6.0.6 on 2026-07-21 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_repair_qualitycheck_missing_columns'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-created_at'], 'verbose_name': 'Favorit', 'verbose_name_plural': 'Favorit'},
        ),
    ]
