# Generated by Django 6.0.6 on 2026-07-28 06:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_add_sku_barcode_brand_weight_dims_expiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_reviews', to='products.product')),
            ],
            options={
                'verbose_name': 'Ulasan Tamu',
                'verbose_name_plural': 'Ulasan Tamu',
                'db_table': 'guest_reviews',
                'unique_together': {('order_number', 'product')},
            },
        ),
    ]
