# Generated by Django 6.0.6 on 2026-07-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_add_guest_review'),
        ('stores', '0004_alter_store_city'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', '-created_at'], name='products_is_acti_b753ec_idx'),
        ),
    ]
