# Generated by Django 6.0.6 on 2026-07-30 15:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_add_performance_indexes'),
        ('stores', '0004_alter_store_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='promo',
            index=models.Index(fields=['store', 'is_active', 'start_date', 'end_date'], name='promo_store_active_date_idx'),
        ),
        migrations.AddIndex(
            model_name='promo',
            index=models.Index(fields=['start_date', 'end_date'], name='promo_date_range_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created_at'], name='review_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', 'product'], name='review_user_product_idx'),
        ),
    ]
