# Generated by Django 6.0.6 on 2026-07-30 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_add_promo_and_review_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', '-created_at'], name='favorites_user_id_f73cef_idx'),
        ),
        migrations.AddIndex(
            model_name='productgallery',
            index=models.Index(fields=['product', 'order'], name='product_gal_product_b96c39_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['is_active', 'expired_date'], name='vouchers_is_acti_3c23b6_idx'),
        ),
    ]
