# Generated by Django 6.0.6 on 2026-07-06 01:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_ai_scan_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='detecteditem',
            new_name='ai_detected_session_b9ae1f_idx',
            old_name='ai_detected_items_session_status_idx',
        ),
        migrations.RenameIndex(
            model_name='detecteditem',
            new_name='ai_detected_master__2f619e_idx',
            old_name='ai_detected_items_master_product_idx',
        ),
        migrations.RenameIndex(
            model_name='detecteditem',
            new_name='ai_detected_detecti_15d4da_idx',
            old_name='ai_detected_items_method_idx',
        ),
        migrations.RenameIndex(
            model_name='detecteditem',
            new_name='ai_detected_detecte_7c54b6_idx',
            old_name='ai_detected_items_barcode_idx',
        ),
        migrations.RenameIndex(
            model_name='expirynotification',
            new_name='inventory_e_store_i_05d430_idx',
            old_name='inventory_e_store_n_m3n4o5_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorystock',
            new_name='inventory_s_store_i_0236f4_idx',
            old_name='inventory_s_store_i_d3b9b5_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorystock',
            new_name='inventory_s_batch_i_c55c4c_idx',
            old_name='inventory_s_batch_i_b1f2a3_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorystock',
            new_name='inventory_s_created_21eaff_idx',
            old_name='inventory_s_created_c4d5e6_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorystock',
            new_name='inventory_s_master__a9ce90_idx',
            old_name='inventory_s_master__e7f8g9_idx',
        ),
        migrations.RenameIndex(
            model_name='masterproduct',
            new_name='inventory_m_barcode_b4e772_idx',
            old_name='inventory_m_barcode_a41bde_idx',
        ),
        migrations.RenameIndex(
            model_name='masterproduct',
            new_name='inventory_m_product_948cc2_idx',
            old_name='inventory_m_product_302c3d_idx',
        ),
        migrations.RenameIndex(
            model_name='masterproduct',
            new_name='inventory_m_categor_37d6bf_idx',
            old_name='inventory_m_category_0f3daf_idx',
        ),
        migrations.RenameIndex(
            model_name='masterproduct',
            new_name='inventory_m_brand_043300_idx',
            old_name='inventory_m_brand_0f3daf_idx',
        ),
        migrations.RenameIndex(
            model_name='productbatch',
            new_name='inventory_p_store_i_4940ea_idx',
            old_name='inventory_p_store_s_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='productbatch',
            new_name='inventory_p_expiry__6c66a2_idx',
            old_name='inventory_p_expiry_d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='productbatch',
            new_name='inventory_p_batch_n_4a1c19_idx',
            old_name='inventory_p_batch_n_g7h8i9_idx',
        ),
        migrations.RenameIndex(
            model_name='productbatch',
            new_name='inventory_p_master__35040d_idx',
            old_name='inventory_p_master__j0k1l2_idx',
        ),
        migrations.RenameIndex(
            model_name='smartscansession',
            new_name='ai_scan_ses_store_i_449c03_idx',
            old_name='ai_scan_sessions_store_status_idx',
        ),
        migrations.RenameIndex(
            model_name='smartscansession',
            new_name='ai_scan_ses_user_id_bc3747_idx',
            old_name='ai_scan_sessions_user_idx',
        ),
        migrations.RenameIndex(
            model_name='smartscansession',
            new_name='ai_scan_ses_started_440fb9_idx',
            old_name='ai_scan_sessions_started_at_idx',
        ),
        migrations.AlterField(
            model_name='detecteditem',
            name='confirmed_count',
            field=models.IntegerField(default=0, help_text='User-confirmed quantity before saving', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Jumlah Dikonfirmasi'),
        ),
        migrations.AlterField(
            model_name='detecteditem',
            name='user_notes',
            field=models.TextField(blank=True, help_text='User corrections or notes before saving', verbose_name='Catatan Pengguna'),
        ),
    ]
