# Generated by Django 4.2.30 on 2026-06-02 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('gosend', 'GoSend'), ('grabexpress', 'GrabExpress'), ('maxim', 'Maxim Delivery'), ('antar_sendiri', 'Antar Sendiri')], max_length=30, unique=True, verbose_name='Kode Kurir')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Kurir')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('icon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ikon URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('estimated_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estimasi Waktu')),
                ('base_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Biaya Dasar')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Urutan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Metode Pengiriman',
                'verbose_name_plural': 'Metode Pengiriman',
                'db_table': 'shipping_methods',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='courier_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nomor Kurir'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='driver_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Driver'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nomor Driver'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='estimated_pickup',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estimasi Penjemputan'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Kode Penjemputan'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='courier_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Kurir'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(choices=[('menunggu_konfirmasi', 'Menunggu Konfirmasi'), ('diproses_penjual', 'Diproses Penjual'), ('menunggu_penjemputan', 'Menunggu Penjemputan'), ('kurir_menjemput', 'Kurir Menjemput'), ('dalam_perjalanan', 'Dalam Perjalanan'), ('pesanan_diterima', 'Pesanan Diterima'), ('dibatalkan', 'Dibatalkan')], default='menunggu_konfirmasi', max_length=30, verbose_name='Status Pengiriman'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='estimated_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estimasi Tiba'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Catatan'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kode Tracking'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='orders.shippingmethod', verbose_name='Metode Pengiriman'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.shippingmethod', verbose_name='Metode Pengiriman'),
        ),
    ]
