# Generated by Django 4.2.30 on 2026-06-07 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_shippingmethod_delivery_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pesanan', 'verbose_name_plural': 'Pesanan'},
        ),
    ]
