# Generated by Django 4.2.30 on 2026-06-07 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-created_at'], 'verbose_name': 'Keranjang', 'verbose_name_plural': 'Keranjang'},
        ),
    ]
