# Generated by Django 4.2.30 on 2026-06-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_add_cart_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='buyer_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude Pembeli'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='buyer_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude Pembeli'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Jarak (km)'),
        ),
    ]
