# Generated by Django 6.0.6 on 2026-07-01 03:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_delivery_buyer_latitude_delivery_buyer_longitude_and_more'),
        ('products', '0005_recentlyviewed'),
        ('stores', '0002_alter_store_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=150, verbose_name='Nama Produk (snapshot)')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Jumlah')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Harga Satuan')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('buyer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Pembeli')),
                ('buyer_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='No. HP Pembeli')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('payment_method', models.CharField(choices=[('cash', 'Tunai'), ('transfer', 'Transfer'), ('qris', 'QRIS')], default='cash', max_length=20, verbose_name='Metode Pembayaran')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_sales', to='products.product', verbose_name='Produk')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_offline_sales', to=settings.AUTH_USER_MODEL, verbose_name='Dicatat Oleh')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_sales', to='stores.store', verbose_name='Toko')),
            ],
            options={
                'verbose_name': 'Penjualan Offline',
                'verbose_name_plural': 'Penjualan Offline',
                'db_table': 'offline_sales',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', '-created_at'], name='offline_sal_store_i_831920_idx'), models.Index(fields=['product'], name='offline_sal_product_918314_idx')],
            },
        ),
    ]
