# Generated by Django 6.0.6 on 2026-07-01 03:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_offline_sale_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=10, verbose_name='Biaya Admin'),
        ),
    ]
