# Generated by Django 6.0.6 on 2026-07-01 04:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_admin_fee_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='admin_fee',
        ),
        migrations.AddField(
            model_name='order',
            name='admin_fee_buyer',
            field=models.DecimalField(decimal_places=2, default=Decimal('1500.00'), max_digits=10, verbose_name='Biaya Admin (Buyer)'),
        ),
        migrations.AddField(
            model_name='order',
            name='admin_fee_seller',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=10, verbose_name='Biaya Admin (Seller)'),
        ),
    ]
