# Generated by Django 6.0.6 on 2026-07-06 01:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_ai_detected_items_session_status_idx_ai_detected_session_b9ae1f_idx_and_more'),
        ('orders', '0009_add_admin_fee_back'),
        ('products', '0006_product_reserved_stock'),
        ('stores', '0004_alter_store_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('packing', 'Packing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='packing', max_length=20, verbose_name='Status Packing')),
                ('total_items', models.IntegerField(default=0, verbose_name='Total Item')),
                ('scanned_items', models.IntegerField(default=0, verbose_name='Sudah Di-scan')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Mulai')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Selesai')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_sessions', to='orders.order', verbose_name='Pesanan')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_sessions', to='stores.store', verbose_name='Toko')),
            ],
            options={
                'verbose_name': 'Sesi Packing',
                'verbose_name_plural': 'Sesi Packing',
                'db_table': 'packing_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PackedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Jumlah')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Scan')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packed_items', to='inventory.productbatch', verbose_name='Batch (FEFO)')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packed_items', to='orders.orderitem', verbose_name='Item Pesanan')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packed_items', to='products.product', verbose_name='Produk')),
                ('packing_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packed_items', to='orders.packingsession', verbose_name='Sesi Packing')),
            ],
            options={
                'verbose_name': 'Item Ter-packing',
                'verbose_name_plural': 'Item Ter-packing',
                'db_table': 'packed_items',
            },
        ),
    ]
