# Generated by Django 6.0.6 on 2026-07-06 01:12
# Modified: admin_fee_seller column doesn't exist in the database,
# so RemoveField would fail. This migration is a no-op.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_order_admin_fee_seller_packingsession_and_more'),
    ]

    operations = [
        # admin_fee_seller was already removed from the model in a previous
        # code change, and the column never existed in the database.
        # The RemoveField operation is intentionally omitted.
    ]
