# Generated by Django 6.0.6 on 2026-07-06 12:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_fix_missing_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='admin_fee_seller',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=10, verbose_name='Biaya Admin Seller (legacy)'),
        ),
    ]
