# Generated by Django 6.0.6 on 2026-07-27 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_add_performance_indexes'),
        ('stores', '0004_alter_store_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='courier_provider',
            field=models.CharField(blank=True, choices=[('grabexpress', 'GrabExpress'), ('gosend', 'GoSend'), ('mitra_pengiriman', 'Mitra Pengiriman'), ('antar_sendiri', 'Antar Sendiri'), ('maxim', 'Maxim Delivery')], max_length=30, null=True, verbose_name='Provider Kurir'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Catatan Pengiriman'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='driver_photo_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Foto Driver'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='driver_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Rating Driver'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='estimated_arrival',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Estimasi Sampai'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='gojek_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gojek Order ID'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='grab_delivery_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Grab Delivery ID'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='last_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude Terakhir'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='last_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude Terakhir'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='mitra_delivery_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mitra Delivery ID'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pod_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Catatan POD'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pod_photo',
            field=models.ImageField(blank=True, null=True, upload_to='pod/', verbose_name='Foto POD'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pod_signature',
            field=models.TextField(blank=True, null=True, verbose_name='Tanda Tangan POD'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pod_signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='POD Ditandatangani'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='position_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Update Posisi'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='qr_delivery_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='QR Delivery'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='qr_pickup_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='QR Pickup'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='tracking_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Tracking'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='vehicle_brand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Merk Kendaraan'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='vehicle_color',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Warna Kendaraan'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='vehicle_plate',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nomor Polisi'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipe Kendaraan'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dibatalkan'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Terkirim'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='driver_assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Driver Ditugaskan'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pickup'),
        ),
        migrations.CreateModel(
            name='MitraDeliveryTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standar', max_length=100, verbose_name='Nama Tarif')),
                ('base_fee', models.DecimalField(decimal_places=2, default=5000, max_digits=10, verbose_name='Biaya Dasar')),
                ('price_per_km', models.DecimalField(decimal_places=2, default=2000, max_digits=10, verbose_name='Biaya per Km')),
                ('free_km', models.DecimalField(decimal_places=1, default=2.0, max_digits=5, verbose_name='Km Gratis')),
                ('min_fee', models.DecimalField(decimal_places=2, default=5000, max_digits=10, verbose_name='Minimal Biaya')),
                ('max_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Maksimal Biaya')),
                ('max_distance_km', models.DecimalField(decimal_places=1, default=20.0, max_digits=5, verbose_name='Max Jarak (km)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitra_tariffs', to='stores.store', verbose_name='Toko')),
            ],
            options={
                'verbose_name': 'Tarif Mitra',
                'verbose_name_plural': 'Tarif Mitra',
                'db_table': 'mitra_delivery_tariffs',
            },
        ),
        migrations.CreateModel(
            name='MitraDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Driver')),
                ('phone', models.CharField(max_length=20, verbose_name='Nomor HP')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='drivers/', verbose_name='Foto Driver')),
                ('vehicle_type', models.CharField(blank=True, help_text='Motor, Mobil, Pickup, dll', max_length=50, null=True, verbose_name='Tipe Kendaraan')),
                ('vehicle_brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='Merk')),
                ('vehicle_plate', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nomor Polisi')),
                ('vehicle_color', models.CharField(blank=True, max_length=30, null=True, verbose_name='Warna')),
                ('status', models.CharField(choices=[('available', 'Tersedia'), ('on_delivery', 'Sedang Mengantar'), ('offline', 'Offline'), ('inactive', 'Nonaktif')], default='available', max_length=20, verbose_name='Status')),
                ('service_area', models.CharField(blank=True, help_text='Kecamatan atau radius yang dilayani', max_length=255, null=True, verbose_name='Area Layanan')),
                ('max_distance_km', models.DecimalField(decimal_places=1, default=10.0, max_digits=5, verbose_name='Max Jarak (km)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('position_updated_at', models.DateTimeField(blank=True, null=True)),
                ('total_deliveries', models.IntegerField(default=0, verbose_name='Total Pengiriman')),
                ('rating_avg', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='Rating Rata-rata')),
                ('auth_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Token Autentikasi')),
                ('fcm_token', models.CharField(blank=True, max_length=500, null=True, verbose_name='FCM Token')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitra_drivers', to='stores.store', verbose_name='Toko')),
            ],
            options={
                'verbose_name': 'Driver Mitra',
                'verbose_name_plural': 'Driver Mitra',
                'db_table': 'mitra_drivers',
                'ordering': ['-total_deliveries'],
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='orders.mitradriver', verbose_name='Driver Ditugaskan'),
        ),
        migrations.AddIndex(
            model_name='mitradriver',
            index=models.Index(fields=['store', 'status'], name='mitra_drive_store_i_aed095_idx'),
        ),
        migrations.AddIndex(
            model_name='mitradriver',
            index=models.Index(fields=['store', 'is_active'], name='mitra_drive_store_i_e0e7d4_idx'),
        ),
    ]
