# Generated by Django 6.0.6 on 2026-07-28 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_delivery_full_fields'),
        ('products', '0011_add_guest_review'),
        ('stores', '0004_alter_store_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', '-created_at'], name='cart_user_id_5db304_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['delivery_status'], name='deliveries_deliver_db2090_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['courier_provider', 'delivery_status'], name='deliveries_courier_b683ec_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_status'], name='orders_order_s_0d3802_idx'),
        ),
        migrations.AddIndex(
            model_name='packingsession',
            index=models.Index(fields=['order', 'status'], name='packing_ses_order_i_6d8d26_idx'),
        ),
        migrations.AddIndex(
            model_name='packingsession',
            index=models.Index(fields=['store', 'status'], name='packing_ses_store_i_5ebeba_idx'),
        ),
    ]
