# Generated by Django 6.0.6 on 2026-06-27 16:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_add_cart_ordering'),
        ('stores', '0002_alter_store_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='No. Refund')),
                ('reason', models.CharField(choices=[('wrong_product', 'Produk Tidak Sesuai'), ('product_damaged', 'Produk Rusak/Cacat'), ('not_as_described', 'Tidak Sesuai Deskripsi'), ('expired', 'Produk Kadaluarsa'), ('missing_items', 'Barang Kurang'), ('defective', 'Produk Cacat'), ('change_mind', 'Berubah Pikiran'), ('other', 'Lainnya')], default='other', max_length=30, verbose_name='Alasan Refund')),
                ('reason_text', models.TextField(blank=True, null=True, verbose_name='Penjelasan Alasan')),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Jumlah Diminta')),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Jumlah Disetujui')),
                ('refund_status', models.CharField(choices=[('pending', 'Menunggu Review'), ('under_review', 'Sedang Ditinjau'), ('waiting_buyer', 'Menunggu Pembeli'), ('waiting_seller', 'Menunggu Penjual'), ('approved', 'Disetujui'), ('rejected', 'Ditolak'), ('cancelled', 'Dibatalkan'), ('refunded', 'Telah Direfund'), ('partial_refund', 'Refund Sebagian')], default='pending', max_length=20, verbose_name='Status Refund')),
                ('resolution', models.CharField(blank=True, choices=[('full_refund', 'Refund Penuh'), ('partial_refund', 'Refund Sebagian'), ('replacement', 'Penggantian Barang'), ('store_credit', 'Kredit Toko'), ('no_refund', 'Tidak Ada Refund')], max_length=20, null=True, verbose_name='Resolusi')),
                ('evidence_images', models.JSONField(blank=True, default=list, help_text='List of uploaded image URLs', verbose_name='Bukti Foto/Video')),
                ('evidence_description', models.TextField(blank=True, null=True, verbose_name='Deskripsi Bukti')),
                ('buyer_notes', models.TextField(blank=True, null=True, verbose_name='Catatan Pembeli')),
                ('seller_notes', models.TextField(blank=True, null=True, verbose_name='Catatan Penjual')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Catatan Admin')),
                ('refund_items', models.JSONField(blank=True, default=list, help_text='[{"item_id": 1, "qty": 2, "product_name": "Bayam Segar"}]', verbose_name='Item yang Direfund')),
                ('is_escalated', models.BooleanField(default=False, verbose_name='Dirujuk ke Admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Selesai')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='orders.order', verbose_name='Pesanan')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='stores.store', verbose_name='Toko')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to=settings.AUTH_USER_MODEL, verbose_name='Pembeli')),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refund',
                'db_table': 'refunds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Refund Diajukan'), ('review_started', 'Review Dimulai'), ('seller_responded', 'Penjual Merespon'), ('buyer_responded', 'Pembeli Merespon'), ('approved', 'Refund Disetujui'), ('rejected', 'Refund Ditolak'), ('cancelled', 'Refund Dibatalkan'), ('refunded', 'Dana Direfund'), ('partial_refunded', 'Refund Sebagian'), ('escalated', 'Dirujuk ke Admin'), ('admin_intervened', 'Admin Turun Tangan'), ('resolved', 'Selesai'), ('evidence_added', 'Bukti Ditambahkan'), ('note_added', 'Catatan Ditambahkan'), ('negotiated', 'Negosiasi Harga')], max_length=30, verbose_name='Tipe Kejadian')),
                ('description', models.TextField(verbose_name='Deskripsi')),
                ('created_by_role', models.CharField(blank=True, max_length=20, null=True, verbose_name='Peran Pembuat')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Data Tambahan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='refunds.refund', verbose_name='Refund')),
            ],
            options={
                'verbose_name': 'Kejadian Timeline Refund',
                'verbose_name_plural': 'Kejadian Timeline Refund',
                'db_table': 'refund_timeline',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['order', 'refund_status'], name='refunds_order_i_1e4485_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['user', 'refund_status'], name='refunds_user_id_cf93a5_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['store', 'refund_status'], name='refunds_store_i_fb5dfe_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['refund_number'], name='refunds_refund__a55d04_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['refund_status'], name='refunds_refund__006cd4_idx'),
        ),
    ]
