# Generated by Django 4.2.30 on 2026-06-02 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='free', max_length=100, verbose_name='Paket')),
                ('start_date', models.DateField(verbose_name='Tanggal Mulai')),
                ('end_date', models.DateField(verbose_name='Tanggal Berakhir')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20, verbose_name='Status')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='Perpanjang Otomatis')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Jumlah Dibayar')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Metode Pembayaran')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='stores.store', verbose_name='Toko')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'Langganan',
                'verbose_name_plural': 'Langganan',
                'db_table': 'subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='subscriptio_user_id_aa8bc6_idx'), models.Index(fields=['store'], name='subscriptio_store_i_a5f620_idx'), models.Index(fields=['status'], name='subscriptio_status_572d44_idx'), models.Index(fields=['end_date'], name='subscriptio_end_dat_763002_idx')],
            },
        ),
    ]
