CREATE TABLE IF NOT EXISTS partner_registrations (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    store_name VARCHAR(120) NOT NULL,
    category VARCHAR(80) NOT NULL,
    description VARCHAR(300) NOT NULL,
    address VARCHAR(255) NOT NULL,
    district VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    province VARCHAR(100) NOT NULL,
    postal_code CHAR(5) NOT NULL,
    latitude DECIMAL(10, 7) NOT NULL,
    longitude DECIMAL(10, 7) NOT NULL,
    store_phone VARCHAR(30) NOT NULL,
    store_email VARCHAR(150) NULL,
    owner_name VARCHAR(120) NOT NULL,
    owner_phone VARCHAR(30) NOT NULL,
    owner_email VARCHAR(150) NOT NULL,
    identity_number CHAR(16) NOT NULL,
    open_time CHAR(5) NOT NULL,
    close_time CHAR(5) NOT NULL,
    minimum_order DECIMAL(12, 2) NOT NULL DEFAULT 0,
    delivery_services JSON NOT NULL,
    service_area ENUM('Seluruh Kota', 'Area Tertentu', 'Pilih Manual') NOT NULL,
    bank_name VARCHAR(80) NOT NULL,
    account_holder VARCHAR(120) NOT NULL,
    account_number VARCHAR(40) NOT NULL,
    status ENUM('pending_verification', 'verified', 'rejected') NOT NULL DEFAULT 'pending_verification',
    rejection_reason VARCHAR(255) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_partner_identity_number (identity_number),
    KEY idx_partner_status (status),
    KEY idx_partner_location (province, city, district),
    KEY idx_partner_store_name (store_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
